#!/usr/bin/env bash
# tools/dev/setup-local-nginx.sh — generate and enable local dev nginx
# vhosts for every site, from tools/dev/nginx-site.conf.template.
#
# Build-output convention: each site's Frozen-Flask output lands at
# sites/<site>/build/ (already anticipated in .gitignore) — this script
# points each vhost's root there. Server-name-based routing
# (<site>.web-sites.test), not port-based, to mirror prod's actual
# routing behavior (see planning/architecture.md's Dev environment
# section).
#
# Idempotent and extendable: re-run any time, including after adding a
# new site to SITES below — existing /etc/hosts entries and vhost files
# are only added if missing, never duplicated.
#
# NOTE: needs sudo (writes /etc/nginx/, /etc/hosts) — sudo on ubuvm
# requires interactive password auth, so Claude cannot run this
# unattended. David runs it directly.
#
# Usage:
#   bash tools/dev/setup-local-nginx.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TEMPLATE="$REPO_ROOT/tools/dev/nginx-site.conf.template"

# The 7 confirmed properties (planning/target-sites.md). Add a new site
# here when it's ready for local dev serving — everything else in this
# script picks it up automatically.
SITES=(taiji spain comunidad movement play music callejerez genuinemerit davidstitt)

echo "[1/4] Generating and enabling vhosts"
for site in "${SITES[@]}"; do
    conf="/etc/nginx/sites-available/${site}.web-sites.test.conf"
    # sed needs no sudo (the template is ours to read) - render to a
    # plain variable first, then a single sudo call to write it. Piping
    # two separate `sudo` calls together (the original version of this
    # script) starts both concurrently, which can produce two
    # overlapping password prompts on the same terminal - confusing and
    # error-prone. One sudo call per site, not two.
    rendered="$(sed -e "s|SITE_NAME|${site}|g" -e "s|REPO_ROOT|${REPO_ROOT}|g" "$TEMPLATE")"
    echo "$rendered" | sudo tee "$conf" > /dev/null
    sudo ln -sf "$conf" "/etc/nginx/sites-enabled/$(basename "$conf")"
    mkdir -p "$REPO_ROOT/sites/${site}/build"
    echo "  - ${site}.web-sites.test -> sites/${site}/build"
done

echo "[2/4] /etc/hosts entries"
for site in "${SITES[@]}"; do
    host="${site}.web-sites.test"
    if ! grep -q "[[:space:]]${host}\$" /etc/hosts; then
        echo "127.0.0.1 ${host}" | sudo tee -a /etc/hosts > /dev/null
        echo "  - added ${host}"
    else
        echo "  - ${host} already present, skipped"
    fi
done

echo "[3/4] Default page (replaces Ubuntu's stock \"Welcome to nginx!\")"
# Any request naming no dev vhost (http://localhost/, the VM's IP) gets
# sites/default/build - the same page the droplet's default server
# shows. Ubuntu's stock default site is disabled (not deleted; re-enable
# with: sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/).
default_conf="/etc/nginx/sites-available/00-default.web-sites.test.conf"
rendered="$(cat <<CONF
# Generated by tools/dev/setup-local-nginx.sh - local dev only.
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    # Relative redirects: keeps the tunnel's :8080 (see the site template).
    absolute_redirect off;
    root ${REPO_ROOT}/sites/default/build;
    index index.html;
    # Prod picks the language from Accept-Language (tested by
    # tools/dev/test-nginx-local.sh); dev just opens English.
    location = / {
        return 302 /en-US/;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
}
CONF
)"
echo "$rendered" | sudo tee "$default_conf" > /dev/null
sudo ln -sf "$default_conf" "/etc/nginx/sites-enabled/$(basename "$default_conf")"
sudo rm -f /etc/nginx/sites-enabled/default
echo "  - default server -> sites/default/build"

echo "[4/4] Testing and reloading nginx"
sudo nginx -t
sudo systemctl reload nginx

echo
echo "[DONE] Try: curl -I http://taiji.web-sites.test/ (302 to /en-US/), and"
echo "       curl -I http://localhost/ (the default page). Build first:"
echo "       bash tools/dev/pre-build-check.sh"
